// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package auditdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advisoryLockChain = `-- name: AdvisoryLockChain :exec
SELECT pg_advisory_xact_lock(0)
`

func (q *Queries) AdvisoryLockChain(ctx context.Context) error {
	_, err := q.db.Exec(ctx, advisoryLockChain)
	return err
}

const getLatestHash = `-- name: GetLatestHash :one
SELECT hash FROM audit_events ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestHash(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, getLatestHash)
	var hash string
	err := row.Scan(&hash)
	return hash, err
}

const insertEvent = `-- name: InsertEvent :one
INSERT INTO audit_events (proposal_hash, kind, payload, prev_hash, hash, at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertEventParams struct {
	ProposalHash string             `db:"proposal_hash" json:"proposal_hash"`
	Kind         string             `db:"kind" json:"kind"`
	Payload      []byte             `db:"payload" json:"payload"`
	PrevHash     string             `db:"prev_hash" json:"prev_hash"`
	Hash         string             `db:"hash" json:"hash"`
	At           pgtype.Timestamptz `db:"at" json:"at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.ProposalHash,
		arg.Kind,
		arg.Payload,
		arg.PrevHash,
		arg.Hash,
		arg.At,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listAllEvents = `-- name: ListAllEvents :many
SELECT id, proposal_hash, kind, payload, prev_hash, hash, at
FROM audit_events
ORDER BY id
`

func (q *Queries) ListAllEvents(ctx context.Context) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAllEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProposalHash,
			&i.Kind,
			&i.Payload,
			&i.PrevHash,
			&i.Hash,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByProposal = `-- name: ListEventsByProposal :many
SELECT id, proposal_hash, kind, payload, prev_hash, hash, at
FROM audit_events
WHERE proposal_hash = $1
ORDER BY id
`

func (q *Queries) ListEventsByProposal(ctx context.Context, proposalHash string) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listEventsByProposal, proposalHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.ProposalHash,
			&i.Kind,
			&i.Payload,
			&i.PrevHash,
			&i.Hash,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateEvents = `-- name: TruncateEvents :exec
TRUNCATE audit_events RESTART IDENTITY
`

func (q *Queries) TruncateEvents(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateEvents)
	return err
}
