// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auditdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID           int64              `db:"id" json:"id"`
	ProposalHash string             `db:"proposal_hash" json:"proposal_hash"`
	Kind         string             `db:"kind" json:"kind"`
	Payload      []byte             `db:"payload" json:"payload"`
	PrevHash     string             `db:"prev_hash" json:"prev_hash"`
	Hash         string             `db:"hash" json:"hash"`
	At           pgtype.Timestamptz `db:"at" json:"at"`
}
